import io
import json
import re
import pandas as pd
import pypdf
import xmltodict


def parse_iredes_xml(xml_bytes):
  try:
    text = (
        xml_bytes.decode("utf-8", errors="ignore")
        if isinstance(xml_bytes, bytes)
        else xml_bytes
    )
    gen_by_match = re.search(r"<!--\s*Generated by\s*([^-]+)-->", text)
    generated_by = gen_by_match.group(1).strip() if gen_by_match else "QuarryX"

    data = xmltodict.parse(text)
    drp = data.get("DRPPlan", {})
    gen_head = drp.get("IR:GenHead", {})
    drill_plan = drp.get("DrillPlan", {})
    opt_data = drill_plan.get("EquipmentData", {}).get("OptionData", {})

    holes = drill_plan.get("Hole", [])
    if isinstance(holes, dict):
      holes = [holes]

    extracted_holes = []
    for h in holes:
      sp = h.get("StartPoint", {})
      ep = h.get("EndPoint", {})
      extracted_holes.append({
          "Hole": str(h.get("HoleName", "")).strip(),
          "BitDia_XML_mm": float(h.get("DrillBitDia", 100)),
          "TypeOfHole": str(h.get("TypeOfHole", "")),
          "XML_StartX": (
              float(sp.get("IR:PointX"))
              if sp.get("IR:PointX") is not None
              else None
          ),
          "XML_StartY": (
              float(sp.get("IR:PointY"))
              if sp.get("IR:PointY") is not None
              else None
          ),
          "XML_StartZ": (
              float(sp.get("IR:PointZ"))
              if sp.get("IR:PointZ") is not None
              else None
          ),
          "XML_EndX": (
              float(ep.get("IR:PointX"))
              if ep.get("IR:PointX") is not None
              else None
          ),
          "XML_EndY": (
              float(ep.get("IR:PointY"))
              if ep.get("IR:PointY") is not None
              else None
          ),
          "XML_EndZ": (
              float(ep.get("IR:PointZ"))
              if ep.get("IR:PointZ") is not None
              else None
          ),
      })

    return {
        "status": "success",
        "generated_by": generated_by,
        "creation_date": gen_head.get(
            "IR:FileCreateDate", drp.get("IR:FileCreateDate", "N/A")
        ),
        "plan_name": drp.get("IR:PlanName", "N/A"),
        "author": drp.get("IR:Comment", "N/A"),
        "project": drp.get("IR:Project", "N/A"),
        "work_order": drp.get("IR:WorkOrder", "N/A"),
        "holes_count": int(
            drill_plan.get("NumberOfHoles", len(extracted_holes))
        ),
        "first_row_burden": float(opt_data.get("FirstRowBurden", 0)),
        "spacing": float(opt_data.get("Spacing", 0)),
        "cubic_mass_m3": float(opt_data.get("CubicMass", 0)),
        "holes": extracted_holes,
    }
  except Exception as e:
    return {"status": "error", "message": str(e)}


def parse_quarryx_csv(csv_bytes):
  try:
    text = (
        csv_bytes.decode("utf-8", errors="ignore")
        if isinstance(csv_bytes, bytes)
        else csv_bytes
    )
    lines = [l.strip() for l in text.strip().splitlines() if l.strip()]
    if not lines:
      return {"status": "error", "message": "Pusty plik"}

    first_line = lines[0]
    sep = "\t" if "\t" in first_line else ";"
    has_header = any(
        k in first_line for k in ["Hole", "Angle", "Azimuth", "BottomX"]
    )

    standard_cols = [
        "Hole",
        "X",
        "Y",
        "Z",
        "BottomX",
        "BottomY",
        "BottomZ",
        "Angle",
        "Azimuth",
        "Length",
        "Floorlevel",
        "Vertical face height",
        "Avg. burden",
        "Profile area",
        "Deck 1 timing",
        "Deck 2 timing",
        "Deck 3 timing",
        "Explosives Design",
        "Explosives Actual",
        "Charge length design",
        "Charge length design without stemming",
        "Charge length actual",
        "Charge length actual without stemming",
        "Hole diameter",
        "Comment",
    ]

    if has_header:
      df = pd.read_csv(io.StringIO(text), sep=sep)
      df.columns = [c.strip() for c in df.columns]
    else:
      df = pd.read_csv(io.StringIO(text), sep=sep, header=None)
      df.columns = standard_cols[: df.shape[1]]

    for col in df.columns:
      if col not in ["Hole", "Comment"]:
        df[col] = df[col].astype(str).str.replace(",", ".").str.strip()
        try:
          df[col] = pd.to_numeric(df[col])
        except Exception:
          pass

    df["Hole"] = df["Hole"].astype(str).str.strip()
    return {
        "status": "success",
        "holes_count": len(df),
        "total_length_m": round(
            float(df["Length"].sum() if "Length" in df.columns else 0.0), 2
        ),
        "total_explosives_kg": round(
            float(
                df["Explosives Design"].sum()
                if "Explosives Design" in df.columns
                else 0.0
            ),
            2,
        ),
        "dataframe": df,
    }
  except Exception as e:
    return {"status": "error", "message": str(e)}


def parse_txt_file(txt_bytes):
  """Parsuje pliki TXT wyciągając kluczowe metryki zabioru: Crest, Toe, Min, Max, Średnia oraz JSON profilu."""
  try:
    text = (
        txt_bytes.decode("utf-8", errors="ignore")
        if isinstance(txt_bytes, bytes)
        else txt_bytes
    )
    raw_shotholes = re.split(r"Shothole\s*:\s*", text)
    holes_data = []

    for block in raw_shotholes:
      if not block.strip():
        continue

      lines = [l.strip() for l in block.strip().splitlines() if l.strip()]
      hole_name = lines[0].strip()

      hole_dict = {
          "Hole": str(hole_name),
          "Coordinates": None,
          "Angle": None,
          "Azimuth": None,
          "Depth": None,
          "Crest_Burden_m": None,
          "Toe_Burden_m": None,
          "Min_Burden_m": None,
          "Min_Burden_Depth_m": None,
          "Max_Burden_m": None,
          "Max_Burden_Depth_m": None,
          "Mean_Burden_m": None,
          "Burden_Profile_JSON": None,
          "Burden_Master_List": [],
      }

      current_section = None
      b_master_pts = []

      for line in lines[1:]:
        if line.startswith("Co-Ordinates"):
          hole_dict["Coordinates"] = line.split(":", 1)[-1].strip()
        elif line.startswith("Hole Angle"):
          val = line.split(":", 1)[-1].strip().replace(",", ".")
          hole_dict["Angle"] = float(val) if val else None
        elif line.startswith("Hole Az"):
          val = line.split(":", 1)[-1].strip().replace(",", ".")
          hole_dict["Azimuth"] = float(val) if val else None
        elif line.startswith("Hole Depth"):
          val = line.split(":", 1)[-1].strip().replace(",", ".")
          hole_dict["Depth"] = float(val) if val else None
        elif "Burden Master Data" in line:
          current_section = "Burden Master Data"
        elif "Profile Data" in line:
          current_section = "Profile Data"
        else:
          parts = line.split(";")
          if current_section == "Burden Master Data" and len(parts) >= 2:
            try:
              depth = float(parts[0].replace(",", "."))
              burden = float(parts[1].replace(",", "."))
              b_master_pts.append({"depth": depth, "burden": burden})
            except Exception:
              pass

      if b_master_pts:
        depths = [p["depth"] for p in b_master_pts]
        burdens = [p["burden"] for p in b_master_pts]

        min_val = min(burdens)
        max_val = max(burdens)

        hole_dict["Crest_Burden_m"] = burdens[0]
        hole_dict["Toe_Burden_m"] = burdens[-1]
        hole_dict["Min_Burden_m"] = min_val
        hole_dict["Min_Burden_Depth_m"] = depths[burdens.index(min_val)]
        hole_dict["Max_Burden_m"] = max_val
        hole_dict["Max_Burden_Depth_m"] = depths[burdens.index(max_val)]
        hole_dict["Mean_Burden_m"] = round(sum(burdens) / len(burdens), 2)
        hole_dict["Burden_Profile_JSON"] = json.dumps(b_master_pts)
        hole_dict["Burden_Master_List"] = b_master_pts

      holes_data.append(hole_dict)

    return {
        "status": "success",
        "holes_count": len(holes_data),
        "holes": holes_data,
    }
  except Exception as e:
    return {"status": "error", "message": str(e)}


def parse_detonator_pdf(pdf_bytes):
  try:
    reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
    full_text = ""
    for page in reader.pages:
      text = page.extract_text()
      if text:
        full_text += text + "\n"

    eng_match = re.search(r"Blasting Engineer[:\.]?\s*([^\n\r]+)", full_text)
    client_match = re.search(r"Client[:\.]?\s*([^\n\r]+)", full_text)
    site_match = re.search(r"Site[:\.]?\s*([^\n\r]+)", full_text)
    proj_match = re.search(r"Project[:\.]?\s*([^\n\r]+)", full_text)
    date_match = re.search(r"Date Of Blast\s*([0-9\.\-]+)", full_text)

    return {
        "status": "success",
        "engineer": eng_match.group(1).strip() if eng_match else "N/A",
        "client": client_match.group(1).strip() if client_match else "N/A",
        "site": site_match.group(1).strip() if site_match else "N/A",
        "project": proj_match.group(1).strip() if proj_match else "N/A",
        "blast_date": date_match.group(1).strip() if date_match else "N/A",
        "euronel_connectors": len(re.findall(r"Euronel Connector", full_text)),
        "surface_connectadets": len(
            re.findall(r"Exel™\s*Connectadet™|Connectadet", full_text)
        ),
    }
  except Exception as e:
    return {"status": "error", "message": str(e)}


def build_master_dataframe(parsed_files):
  df_base = None

  if "csv" in parsed_files and "dataframe" in parsed_files["csv"]:
    df_base = parsed_files["csv"]["dataframe"].copy()

  if "xml" in parsed_files and "holes" in parsed_files["xml"]:
    df_xml = pd.DataFrame(parsed_files["xml"]["holes"])
    if df_base is not None:
      df_base = df_base.merge(df_xml, on="Hole", how="outer")
    else:
      df_base = df_xml

  if "txt" in parsed_files and "holes" in parsed_files["txt"]:
    txt_rows = []
    for h in parsed_files["txt"]["holes"]:
      txt_rows.append({
          "Hole": str(h["Hole"]).strip(),
          "TXT_Coordinates": h["Coordinates"],
          "TXT_Angle": h["Angle"],
          "TXT_Azimuth": h["Azimuth"],
          "TXT_Depth": h["Depth"],
          "Crest_Burden_m": h["Crest_Burden_m"],
          "Toe_Burden_m": h["Toe_Burden_m"],
          "Min_Burden_m": h["Min_Burden_m"],
          "Min_Burden_Depth_m": h["Min_Burden_Depth_m"],
          "Max_Burden_m": h["Max_Burden_m"],
          "Max_Burden_Depth_m": h["Max_Burden_Depth_m"],
          "Mean_Burden_m": h["Mean_Burden_m"],
          "Burden_Profile_JSON": h["Burden_Profile_JSON"],
      })
    df_txt = pd.DataFrame(txt_rows)
    if df_base is not None:
      df_base = df_base.merge(df_txt, on="Hole", how="outer")
    else:
      df_base = df_txt

  if df_base is not None and not df_base.empty:
    if "X" not in df_base.columns and "XML_StartX" in df_base.columns:
      df_base["X"] = df_base["XML_StartX"]
      df_base["Y"] = df_base["XML_StartY"]
      df_base["Z"] = df_base["XML_StartZ"]
      df_base["BottomX"] = df_base["XML_EndX"]
      df_base["BottomY"] = df_base["XML_EndY"]
      df_base["BottomZ"] = df_base["XML_EndZ"]

    if "Length" not in df_base.columns and "TXT_Depth" in df_base.columns:
      df_base["Length"] = df_base["TXT_Depth"]

    if "Angle" not in df_base.columns and "TXT_Angle" in df_base.columns:
      df_base["Angle"] = df_base["TXT_Angle"]
      df_base["Azimuth"] = df_base["TXT_Azimuth"]

  return df_base